---
title: "Rough Work for Model Building"
author: "Luke Fields (8385924)"
date: "`r format(Sys.Date(), 'November 28, 2022')`"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

Below are the packages and libraries we are using in this assignment. 
  
```{r setup, message = FALSE}
library(corrplot)
library(klaR) 
library(knitr)
library(MASS)
library(tidyverse)
library(tidymodels)
library(ggplot2)
library("dplyr")
library("yardstick")
library(stringr)
tidymodels_prefer()
knitr::opts_chunk$set(
	echo = TRUE,
	fig.height = 5,
	fig.width = 7,
	tidy = TRUE,
	tidy.opts = list(width.cutoff = 60)
)
opts_chunk$set(tidy.opts=list(width.cutoff=60),tidy=TRUE)
options(digits = 4)
## indents are for indenting r code as formatted text
## They may need to be adjusted depending on your OS
# if your output looks odd, increase or decrease indent
indent1 = '    '
indent2 = '        '
indent3 = '            '
```

```{r}
set.seed(1040)
student_mh_clean <- read_csv("/Users/lukefields/Desktop/pstat197/vignette-binary-class-bootstrap/data/student_mh_clean.csv")

student_mh_clean <- student_mh_clean %>%
  mutate(Married = factor(Married, levels = c("Yes", "No")),
         Depression = factor(Depression, levels = c("Yes", "No")),
         Anxiety = factor(Anxiety, levels = c("Yes", "No")),
         Panic_Attack = factor(Panic_Attack, levels = c("Yes", "No")),
         Seek_Help = factor(Seek_Help, levels = c("Yes", "No")),)

```


Let's do some model building with logistic regression
```{r}
student_mh_dep_split <- initial_split(student_mh_clean, 
                               prop = 0.6, strata = Depression)
student_mh_dep_train <- training(student_mh_dep_split)
student_mh_dep_test <- testing(student_mh_dep_split)

student_mh_dep_recipe <- 
  recipe(Depression ~ ., data = student_mh_dep_train) %>%
  step_rm(Major) %>%
  step_rm(Anxiety) %>%
  step_dummy(all_nominal_predictors())

student_mh_dep_log_reg <- logistic_reg() %>% 
  set_engine("glm") %>% 
  set_mode("classification")

student_mh_dep_log_wf <- workflow() %>% 
  add_model(student_mh_dep_log_reg) %>% 
  add_recipe(student_mh_dep_recipe)

student_mh_dep_fit <- fit(student_mh_dep_log_wf, student_mh_dep_train)

student_mh_dep_pred <- predict(student_mh_dep_fit, new_data = student_mh_dep_test, type = "class") %>% 
  bind_cols(student_mh_dep_test) 

student_mh_dep_acc <- student_mh_dep_perf %>% 
  accuracy(truth = Depression, estimate = .pred_class)

student_mh_dep_pred <- student_mh_dep_pred %>%
  rename(Pred_Depression = .pred_class)

student_mh_dep_pred

student_mh_dep_acc
```
Depression at like an 80.65% accuracy. 

```{r}
student_mh_anx_split <- initial_split(student_mh_clean, 
                               prop = 0.7, strata = Anxiety)
student_mh_anx_train <- training(student_mh_anx_split)
student_mh_anx_test <- testing(student_mh_anx_split)

student_mh_anx_recipe <- 
  recipe(Anxiety ~ ., data = student_mh_anx_train) %>%
  step_rm(Major) %>%
  step_rm(Depression) %>%
  step_dummy(all_nominal_predictors())

student_mh_anx_log_reg <- logistic_reg() %>% 
  set_engine("glm") %>% 
  set_mode("classification")

student_mh_anx_log_wf <- workflow() %>% 
  add_model(student_mh_anx_log_reg) %>% 
  add_recipe(student_mh_anx_recipe)

student_mh_anx_fit <- fit(student_mh_anx_log_wf, student_mh_anx_train)

student_mh_anx_pred <- predict(student_mh_anx_fit, new_data = student_mh_anx_test, type = "class") %>%
  bind_cols(student_mh_anx_test) 


student_mh_anx_acc <- student_mh_anx_pred %>% 
  accuracy(truth = Anxiety, estimate = .pred_class)

student_mh_anx_pred <- student_mh_anx_pred %>%
  rename(Pred_Anxiety = .pred_class)

student_mh_anx_pred

student_mh_anx_acc
```




Trying out Thomas' boosted tree model on Anxiety
```{r}
set.seed(117)
student_mh_split <- student_mh_clean %>% initial_split(strata = Anxiety, prop = 0.6)
student_mh_train <- training(student_mh_split)
student_mh_test <- testing(student_mh_split)

boost_tree_model <- boost_tree() %>%
  set_engine("xgboost") %>%
  set_mode("classification")
boost_recipe <- 
  recipe(Anxiety ~ ., data = student_mh_train) %>%
  step_rm(Depression) %>%
  step_dummy(all_nominal_predictors())
boost_wkf <- workflow() %>% 
  add_model(boost_tree_model) %>%
  add_recipe(boost_recipe)

boost_tree_fit <- fit(boost_wkf, student_mh_train)

boost_pred <- predict(boost_tree_fit, new_data = student_mh_test, type = "class") %>% 
  bind_cols(student_mh_test) 

student_mh_acc <- boost_pred %>% 
  accuracy(truth = Anxiety, estimate = .pred_class)

student_mh_acc
```
63% accuracy for anxiety

Trying out Thomas' boosted tree model on Seek help
```{r}
set.seed(117)
student_mh_split <- student_mh_clean %>% initial_split(strata = Seek_Help, prop = 0.6)
student_mh_train <- training(student_mh_split)
student_mh_test <- testing(student_mh_split)

boost_tree_model <- boost_tree() %>%
  set_engine("xgboost") %>%
  set_mode("classification")
boost_recipe <- 
  recipe(Anxiety ~ ., data = student_mh_train) %>%
  step_rm(Depression) %>%
  step_dummy(all_nominal_predictors())
boost_wkf <- workflow() %>% 
  add_model(boost_tree_model) %>%
  add_recipe(boost_recipe)

boost_tree_fit <- fit(boost_wkf, student_mh_train)

boost_pred <- predict(boost_tree_fit, new_data = student_mh_test, type = "class") %>% 
  bind_cols(student_mh_test) 

student_mh_acc <- boost_pred %>% 
  accuracy(truth = Seek_Help, estimate = .pred_class)

student_mh_acc
```





Lily's boot
```{r}
library(boot)
# function to obtain accuracy from logistic regression
acc_f <- function(formula, data, i) {
  d2 <- data[i,]
  d2_split <- initial_split(d2, prop = 0.7, strata = Anxiety)
  d2_train <- training(d2_split)
  d2_test <- testing(d2_split)
  
  recipe <- 
    recipe(Depression ~ ., d2_train) %>%
    step_rm(Major) %>%
    step_rm(Anxiety) %>%
    step_dummy(all_nominal_predictors())

  log_reg <- logistic_reg() %>% 
    set_engine("glm") %>% 
    set_mode("classification")

  wf <- workflow() %>% 
    add_model(log_reg) %>% 
    add_recipe(recipe)

  fit <- fit(wf, d2_train)

  pred <- predict(fit, new_data = d2_test, type = "class") %>% 
    bind_cols(d2_test) 

  acc <- pred %>% accuracy(truth = Depression, estimate = .pred_class)
  
  return (acc[3] %>% as.numeric())
}

# bootstrapping with 1000 replications
results <- boot(data=student_mh, statistic=acc_f,R=1000, formula=Depression ~ .)

results
plot(results)

# 95% confidence interval
boot.ci(results, type="bca")
```
